config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'materials#index'

  get "signup", to: "users#new"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  
  resources :users, except: [:new]
  resources :materials, except: [:show]

  get "materials/:id/input", to: 'materials#add', as: 'material_add'
  patch "materials/:id/input", to: 'materials#input', as: 'material_input'
  get "materials/:id/output", to: 'materials#remove', as: 'material_remove'
  patch "materials/:id/output", to: 'materials#output', as: 'material_output'
  get "materials/:id/logs", to: 'materials#logs', as: 'material_log'
  delete "materials/:id", to: 'materials#destroy', as: 'material_destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/material.rb
class Material < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :description, presence: true, length: { maximum: 200 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }

  has_many :material_logs

  def update_quantity!(method, quantity, current_user)
    @quantity = quantity.to_i

    if method == "input" && @quantity.negative?
      errors.add(:quantity, "can't be negative")
      return false

    elsif method == "output" && @quantity.positive?
      errors.add(:quantity, "can't be positive")
      return false

    elsif @quantity.zero?
      errors.add(:quantity, "can't be zero")
      return false
    end

    self.update!(quantity: self.quantity += @quantity)
    self.material_logs.create(material_log_params(method, quantity, current_user))
  end

  private 

  def material_log_params(method, quantity, current_user)
    {
      material_id: self.id,
      user_id: current_user.id,
      method: method,
      quantity: quantity.to_i
    }
  end
end

app/models/material_log.rb
class MaterialLog < ApplicationRecord
  validates :quantity, :method, :material_id, :user_id, presence: true
  validates :method, inclusion: { in: %w(input output), message: "%{value} is not valid."}

  belongs_to :material
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, length: { in: 8..30 }

  has_many :material_logs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?, :require_user, :error_messages

  before_action :require_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
   
  def logged_in?
    !!current_user
  end
   
  def require_user
    if !logged_in?
      flash[:warning] = "You must be logged in to perform that action."
      redirect_to login_path
    end
  end

  def error_messages(errors_list)
    text = "Error#{'s' if errors_list.length > 1}: "
    count = 0

    errors_list.each do |error|
      count += 1
      return text += error + '.' if count == errors_list.count

      text += error + ', '
    end

    text
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  before_action :find_material!, except: [:index, :new, :create]

  attr_accessor :material

  def index
    @q = Material.ransack(params[:q])
    @materials = @q.result(distinct: true).page(params[:page]).order(:name)
  end

  def new
    @material = Material.new
  end

  def create
    @material = Material.new(material_params)

    if @material.save
      flash[:success] = "Material created."
      redirect_to materials_path
    else
      flash[:danger] = "#{error_messages(@material.errors.full_messages)}"
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
    @material = material
  end

  def update
    if material.update(material_update_params)
      flash[:success] = "Material edited."
      redirect_to materials_path
    else
      flash[:danger] = "#{error_messages(@material.errors.full_messages)}"
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    if material.material_logs.empty?
      material.destroy!
      flash[:success] = "Material deleted succesfully."
      redirect_to materials_path
    else
      flash[:danger] = "Material has input/output log, so can't be deleted." 
      redirect_back(fallback_location: root_path)
    end
  end
  
  def add
    @material = material
  end
  
  def input
    if material.update_quantity!("input", material_change_quantity_params[:quantity], current_user)
      flash[:success] = "Material inputed."
      redirect_to materials_path
    else
      flash[:danger] = "#{error_messages(@material.errors.full_messages)}"
      redirect_back(fallback_location: root_path)
    end
  end
  
  def remove
    @material = material
  end
  
  def output
    if material.update_quantity!("output", material_change_quantity_params[:quantity], current_user)
      flash[:success] = "Material outputed."
      redirect_to materials_path
    else
      flash[:danger] = "#{error_messages(@material.errors.full_messages)}"
      redirect_back(fallback_location: root_path)
    end
  end

  def logs
    @material = material
    @logs = material.material_logs
  end

  private

  def find_material!
    @material = Material.find(params[:id])
  end

  def material_params
    params.require(:material).permit(:name, :description, :quantity)
  end

  def material_update_params
    params.require(:material).permit(:name, :description)
  end

  def material_change_quantity_params
    params.require(:material).permit(:quantity)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_user, only: [:new, :create]
  before_action :verify_logged_in, only: [:new]

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in succesfully."
      redirect_to materials_path
    else
      flash[:danger] = "There was something wrong with your login attempt."
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have been logged out."
    redirect_to login_path
  end

  private

  def verify_logged_in
    redirect_to root_path if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_user
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "User created."
      redirect_to root_path
    else
      flash[:danger] = "#{error_messages(@user.errors.full_messages)}"
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def convert_date(date)
    date.strftime("%d/%m/%y %H:%M")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>< Depósito ></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  
  </head>

  <body class="root">
    <%= yield %>
  </body>
</html>

app/views/materials/_form.html.erb
<%= form_with(model: material) do |f| %>
    <div class="form-group">
      <%= f.label 'Nome', class: "form-label" %><br/>
      <%= f.text_field :name, class: "form-control mt-2" %>
    </div>

    <div class="form-group">
      <%= f.label 'Descrição', class: "form-label mt-3" %><br/>
      <%= f.text_area :description, class: "form-control mt-2" %>
    </div>

    <% if !edit %>
      <div class="form-group">
        <%= f.label 'Quantidade', class: "form-label mt-3" %><br/>
        <%= f.number_field :quantity, class: "form-control mt-2" %>
      </div>

      <div class="form-group">
        <%= f.submit "Adicionar", class: "btn btn-secondary button-card my-4" %>
      </div>
    <% else %>
      <div class="form-group">
        <%= f.submit "Editar", class: "btn btn-secondary button-card my-4" %>
      </div>
    <% end%>
  <% end %>

app/views/materials/_header.html.erb
<header>
  <div class="header-row" style="width: 100%;">
    <h1><%= link_to "Depósito", materials_path, class: "index_header_link" %></h1>
    <% if logged_in? %>
      <div class="logout-section">
        <p class="username-section">Usuário logado: <%= current_user.username %></p>
        <%= button_to "Sair", logout_path, class: "btn btn-secondary logout-button", method: :delete %>
      </div>
    <% end %>
  </div>
</header>
<% flash.each do |name, message| %>
  <%= content_tag :div, message, class: "alert alert-#{name}" %>
<% end %>

app/views/materials/add.html.erb
<%= render 'header' %>

<main>
  <div class="container">
    <div class="row">
      <div class="col-lg-1"></div>
      <div class="col-lg-10">
        <div class="card card-materials-index container">
          <div class="card-header">
            <div class="container">
              <div class="mt-2">
                <h2>Materiais > Entrada</h2>
              </div>
            </div>
          </div>
          <div class="card-body form-card-body">
            <%= form_with(model: @material, url: material_input_path(@material) ) do |f| %>
              <div class="form-group">
                <%= f.label 'Nome', class: "form-label" %><br/>
                <%= f.text_field :name, class: "form-control mt-2", disabled: true %>
              </div>

              <div class="form-group">
                <%= f.label 'Quantidade', class: "form-label mt-3" %><br/>
                <%= f.number_field :quantity, class: "form-control mt-2", value: 0, min: 0%>
              </div>

              <div class="form-group">
                <%= f.submit "Adicionar", class: "btn btn-secondary button-card my-4" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-lg-1"></div>
    </div>
  </div>
</main>

app/views/materials/edit.html.erb
<%= render 'header' %>

<main>
  <div class="container">
    <div class="row">
      <div class="col-lg-1"></div>
      <div class="col-lg-10">
        <div class="card card-materials-index container">
          <div class="card-header">
            <div class="container">
              <div class="mt-2">
                <h2>Materiais > Editar</h2>
              </div>
            </div>
          </div>
          <div class="card-body form-card-body">
            <%= render 'form', material: @material, edit: true %>
          </div>
        </div>
      </div>
      <div class="col-lg-1"></div>
    </div>
  </div>
</main>

app/views/materials/index.html.erb
<%= render 'header' %>

<main>
  <div class="card card-materials-index container">
    <div class="card-header">
      <div class="container">
        <div class="row d-flex align-items-center">
          <div class="col-sm-12 col-md-4 mt-2 d-flex">
            <h2 class="material-index-table-title">Materiais</h2>
            <%= button_to '+', new_material_path, class: "btn btn-secondary search-button-materials-index", method: :get %>
          </div>
          <div class="col-sm-12 col-md-8 ">
            <%= search_form_for @q do |f| %>
              <div class="container p-0">
                <div class="row search-field-materials-index">
                  <div class="col-3">
                    <%= f.label 'Pesquisa por nome' %>
                  </div>
                  <div class="col-7">
                    <%= f.search_field :name_cont, class: "form-control" %>
                  </div>
                  <div class=" col-2">
                    <%= f.submit 'Procurar', class: "btn btn-secondary search-button-materials-index"%>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <table class="table table-materials-index">
      <tr>
        <th style="width: 20%; padding-left: 28px;">Nome</th>
        <th style="width: 20%">Descrição</th>
        <th style="width: 10%">Quantidade</th>
        <th class="text-center" style="width: 50%; padding-right: 28px;">Ações</th>
      </tr>
      <% if !@materials.empty? %>
        <% @materials.map do |material| %>
          <tr>
            <td style="padding-left: 28px"><%= material.name %></td>
            <td><%= material.description %></td>
            <td><%= material.quantity %></td>
            <td class="text-center">
              <div class="btn-group flex-wrap" style="padding-right: 28px;">
                <%= button_to "+", material_add_path(material.id), class: "btn btn-secondary search-button-materials-index", method: :get %>
                <%= button_to "-", material_remove_path(material.id), class: "btn btn-primary", method: :get %>
                <%= button_to "Log", material_log_path(material.id), class: "btn btn-warning", method: :get %>
                <%= button_to "Remover", material_destroy_path(material.id), class: "btn btn-danger", method: :delete %>
                <%= button_to "Editar", edit_material_path(material.id), class: "btn btn-secondary search-button-materials-index", method: :get %>
              </div>
            </td>
          </tr>
        <% end %>
      <% else %>
        <tr>
          <td style="padding-left: 28px">Nenhum material encontrado.</td>
        </tr>
      <% end %>
    </table>
  </div>
  
  <div class="index-paginate mt-4">
    <%= paginate @materials %>
  </div>
</main>

app/views/materials/logs.html.erb
<%= render 'header' %>

<main>
  <div class="container">
    <div class="row">
      <div class="col-lg-1"></div>
      <div class="col-lg-10">
        <div class="card card-materials-index container">
          <div class="card-header">
            <div class="container">
              <h2>Logs Entrada/Saída > <%= @material.name %></h2>
            </div>
          </div>
          <table class="table table-materials-index">
            <tr>
              <th style="width: 30%; padding-left: 28px;">Usuário</th>
              <th style="width: 20%">Entrada/Saída</th>
              <th style="width: 20%">Quantidade</th>
              <th style="width: 30%">Data/Hora</th>
            </tr>
            <% if @logs.empty? %>
              <tr>
                <td colspan="4">
                  Nenhum registro.
                </td>
              </tr>
            <% else %>
              <% @logs.map do |log| %>
                <tr>
                  <td style="padding-left: 28px"><%= log.user.username %></td>
                  <td><%= log.method %></td>
                  <td><%= log.quantity %></td>
                  <td><%= convert_date(log.created_at) %></td>
                </tr>
              <% end%>
            <% end %>
          </table>
        </div>
      </div>
      <div class="col-lg-1"></div>
    </div>
  </div>
</main>

app/views/materials/new.html.erb
<%= render 'header' %>

<main>
  <div class="container">
    <div class="row">
      <div class="col-lg-1"></div>
      <div class="col-lg-10">
        <div class="card card-materials-index container">
          <div class="card-header">
            <div class="container">
              <div class="mt-2">
                <h2>Materiais > Adicionar</h2>
              </div>
            </div>
          </div>
          <div class="card-body form-card-body">
            <%= render 'form', material: @material, edit: false %>
          </div>
        </div>
      </div>
      <div class="col-lg-1"></div>
    </div>
  </div>
</main>

app/views/materials/remove.html.erb
<%= render 'header' %>

<main>
  <div class="container">
    <div class="row">
      <div class="col-lg-1"></div>
      <div class="col-lg-10">
        <div class="card card-materials-index container">
          <div class="card-header">
            <div class="container">
              <div class="mt-2">
                <h2>Materiais > Saída</h2>
              </div>
            </div>
          </div>
          <div class="card-body form-card-body">
            <%= form_with(model: @material, url: material_output_path(@material) ) do |f| %>
              <div class="form-group">
                <%= f.label 'Nome', class: "form-label" %><br/>
                <%= f.text_field :name, class: "form-control mt-2", disabled: true %>
              </div>

              <div class="form-group">
                <%= f.label 'Quantidade', class: "form-label mt-3"  %><br/>
                <%= f.number_field :quantity, class: "form-control mt-2", value: 0, max: 0%>
              </div>

              <div class="form-group">
                <%= f.submit "Retirar", class: "btn btn-secondary button-card my-4" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-lg-1"></div>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<main>
  <div class="login-title">
    <h1><%= link_to "Depósito", materials_path, class: "index_header_link" %></h1>
    <h2>Registrar</h2>
  </div>
  <div class="container">
    <% flash.each do |name, message| %>
      <%= content_tag :div, message, class: "alert alert-#{name}" %>
    <% end %>
    <div class="row">
      <div class="col-md-0 col-lg-2"></div>
      <div class="col-md-12 col-lg-8">
        <div class="container">
          <div class="card card-login" width="100%">
            <div class="row py-3">
              <div class="col-2"></div>
              <div class="col-8">
                <div class="card-body card-body-edit">
                  <%= form_with(model: @user) do |f| %>
                    <div class="form-group">
                      <%= f.label :Usuário %><br/>
                      <%= f.text_field :username, class: "form-control mt-2" %>
                    </div>

                    <div class="form-group">
                      <%= f.label :Senha, class: 'mt-3' %><br/>
                      <%= f.password_field :password, class: "form-control mt-2" %>
                    </div>

                    <div class="form-group">
                      <%= f.submit "Registrar", class: "btn btn-secondary button-card my-4" %>
                    </div>
                  <% end %>
                </div>
                <div class="col-2"></div>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-0 col-lg-2"></div>
      </div>
    </div>
  </div>
</main>